CREATE DATABASE blog;

CREATE TABLE blog.post (
	post_id INT UNSIGNED AUTO_INCREMENT,
	title VARCHAR(200) DEFAULT '',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT UNSIGNED NOT NULL,
	img VARCHAR(200) NOT NULL,
	likes INT,
	PRIMARY KEY (post_id)
);

CREATE TABLE blog.user (
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(200) DEFAULT '',
	avatar VARCHAR(200) NOT NULL,
	PRIMARY KEY (id)
);